remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: Ярослав Барабанов
description: Разработчик в сфере алготритмической торговли
show_downloads: false
github:
  is_project_page: false
